spring:
  application:
    name: rst-web-management

#数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/rst
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 50MB
      #最大请求大小（包括所有文件和表单数据）
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启了驼峰命名映射开关
    map-underscore-to-camel-case: true
    #指定XML映射配置文件的位置
  mapper-locations: classpath:mapper/*.xml

#配置事物管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: sijidazao-test0
    region: cn-beijing



